const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const C=require('../web/core.js');
const context={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../web/seed.js'),'utf8'),context);
const seed=JSON.parse(JSON.stringify(context.window.STARTER_RECIPES));
test('parses decimal, fraction, mixed and Unicode quantities',()=>{for(const [input,result] of [['2',2],['0.5',.5],['1/2',.5],['1 3/4',1.75],['½',.5],['1½',1.5],['2 ⅓',2+1/3],['',null]])assert.equal(C.quantity(input),result);});
test('rejects ambiguous and invalid quantities',()=>{for(const input of ['1/0','one','1-2','-1','NaN','Infinity','1..2'])assert.ok(Number.isNaN(C.quantity(input)));});
test('formats common fractions without rounding arbitrary numbers to a fraction',()=>{assert.equal(C.fmt(1.5),'1 ½');assert.equal(C.fmt(1/3),'⅓');assert.equal(C.fmt(1.51),'1.51');assert.equal(C.fmt(null),'');});
test('validates both starter drafts',()=>seed.forEach(C.validRecipe));
test('scales the burger batch from 12 to 6 patties without mutating original',()=>{const output=C.scaled(seed[0],6);assert.equal(output[0].amount,1);assert.equal(output[1].amount,1);assert.equal(seed[0].ingredients[0].amount,2);});
test('rejects impossible scaling factors',()=>{for(const n of [0,-1,Infinity,1001])assert.throws(()=>C.scaled(seed[0],n));});
test('preserves unmeasured ingredients when scaled',()=>{const r={...seed[0],ingredients:[{amount:null,unit:'',name:'Salt to taste'}]};assert.equal(C.scaled(r,6)[0].amount,null);});
test('combines same-name, same-unit ingredients across batches',()=>{const list=C.shopping(seed,[{recipeId:seed[0].id,servings:12},{recipeId:seed[1].id,servings:24}]);assert.equal(list.find(x=>x.name==='Badia Complete Seasoning').amount,4);assert.equal(list.filter(x=>x.name==='Worcestershire sauce').length,2);});
test('normalizes kg to g but never volume to mass',()=>{const r={...seed[0],ingredients:[{amount:1,unit:'kg',name:'Flour'},{amount:500,unit:'g',name:'flour'},{amount:1,unit:'cup',name:'Flour'}]};const list=C.shopping([r],[{recipeId:r.id,servings:12}]);assert.equal(list.find(x=>x.unit==='g').amount,1500);assert.equal(list.length,2);});
test('round trips a recipe backup',()=>{const b=C.parseBackup(JSON.stringify({app:'Our Table',schema:1,recipes:seed}));assert.equal(b.recipes.length,2);});
test('rejects unrelated JSON and executable image content',()=>{assert.throws(()=>C.parseBackup('{"recipes":[]}'));const r=structuredClone(seed[0]);r.photo='javascript:alert(1)';assert.throws(()=>C.validRecipe(r));r.photo='data:image/svg+xml;base64,AAAA';assert.throws(()=>C.validRecipe(r));});
test('import preserves existing data and copies conflicts',()=>{const different=structuredClone(seed[0]);different.notes='Less paprika';const result=C.mergeRecipes(seed,[different]);assert.equal(result.recipes.length,3);assert.equal(result.recipes[0].notes,seed[0].notes);assert.equal(result.conflicts,1);assert.notEqual(result.recipes[2].id,seed[0].id);});
test('identical import does not duplicate recipes',()=>{const result=C.mergeRecipes(seed,structuredClone(seed));assert.equal(result.recipes.length,2);assert.equal(result.added,0);});
test('rejects duplicate backup IDs, NaN quantities and oversized histories',()=>{assert.throws(()=>C.parseBackup(JSON.stringify({app:'Our Table',schema:1,recipes:[seed[0],seed[0]]})));const r=structuredClone(seed[0]);r.ingredients[0].amount=NaN;assert.throws(()=>C.validRecipe(r));r.ingredients[0].amount=1;r.history=new Array(21).fill(seed[1]);assert.throws(()=>C.validRecipe(r));});
test('ignores deleted recipes in shopping batches',()=>{assert.deepEqual(C.shopping([],[{recipeId:'missing',servings:4}]),[]);});
